apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-api
  template:
    metadata:
      labels:
        app: my-node-api
    spec:
      containers:
      - name: node-app
        image: my-node-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"


