# This file defines a Kubernetes service for a Node.js API application.
# It exposes the application to the outside world using a LoadBalancer.
apiVersion: v1
kind: Service
metadata:
  name: my-node-api-service
spec:
  type: LoadBalancer
  selector:
    app: my-node-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
